# Generated by Django 3.2.4 on 2021-07-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='id')),
                ('StopSequence', models.IntegerField(verbose_name='StopSequence')),
                ('RouteName', models.CharField(max_length=20, verbose_name='RouteName')),
                ('RouteDescription', models.CharField(max_length=100, verbose_name='RouteDescription')),
                ('Direction', models.CharField(max_length=10, verbose_name='Direction')),
                ('StopID', models.CharField(max_length=50, verbose_name='StopID')),
                ('StopNum', models.CharField(max_length=50, verbose_name='StopNum')),
                ('Latitude', models.FloatField(verbose_name='Latitude')),
                ('Longitude', models.FloatField(verbose_name='Longitude')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Ainm', models.CharField(max_length=100, verbose_name='Ainm')),
                ('HasPole', models.CharField(max_length=30, verbose_name='HasPole')),
                ('HasShelter', models.CharField(max_length=30, verbose_name='HasShelter')),
                ('RouteData', models.CharField(max_length=255, verbose_name='RouteData')),
            ],
        ),
    ]
